version: '3'
services:
  api:
    environment:
      STORAGE_TYPE: postgres
      POSTGRES_DSN: ${POSTGRES_DSN}
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./postgres-init
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5
