version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile.api
    environment:
      STORAGE_TYPE: in-memory
      BASE_URL: ${BASE_URL}
    ports:
      - "50051:50051"
    healthcheck:
      test: [ "CMD", "/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 3
