FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 make build/mock_client

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/bin/mock_client .

CMD ./mock_client