FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.2 && \
    wget -qO/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /grpc_health_probe

COPY . .

RUN make build/api

EXPOSE 50051

CMD ./bin/api -base_url=${BASE_URL} -storage_type=${STORAGE_TYPE} -db-dsn=${POSTGRES_DSN} -limiter-enabled